---
title: "Covid 19 Data Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## <span style="color:red"> Configuration & Set up  </span>


</br>

#### <span style="color:green"> Loading necessary library </span>

```{r message=FALSE}
library("tidyverse")
```

#### <span style="color:green"> Reading in the data</span>

```{r}
corona <- read_csv("data/corona_data.csv")
```


</br>

## <span style="color:red"> Finding the total amount of infected people in Germany over the course of time </span>   

</br>

#### <span style="color:green"> Loading *dplyr* package to use pipes </span>

```{r message=FALSE}    
library("dplyr")
```

#### <span style="color:green"> Grouping infections depending on corresponding day </span>
```{r} 
total_infected_by_day <- corona %>%
                            group_by(date) %>%
                              summarise(total_infected = sum(number_infected))
```

#### <span style="color:green"> View Tibble </span>   

```{r}                           
total_infected_by_day
```



#### <span style="color:green"> Plot it vs data using *geom_line()*</span>

```{r}
ggplot(total_infected_by_day, aes(x = date, y = total_infected)) +
        # Extra paramters optional for better visualization
        geom_line(size=2,col="red") + ylab("Total number of infections") + 
          ggtitle("Amount of total infections over time") 
```